// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mat_G
NumericMatrix mat_G(NumericMatrix d_X, NumericMatrix d_Y);
RcppExport SEXP gwDist_mat_G(SEXP d_XSEXP, SEXP d_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type d_X(d_XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type d_Y(d_YSEXP);
    __result = Rcpp::wrap(mat_G(d_X, d_Y));
    return __result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP gwDist_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// H_mu_typed
double H_mu_typed(NumericMatrix mu, NumericMatrix d_X, NumericMatrix d_Y);
RcppExport SEXP gwDist_H_mu_typed(SEXP muSEXP, SEXP d_XSEXP, SEXP d_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type d_X(d_XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type d_Y(d_YSEXP);
    __result = Rcpp::wrap(H_mu_typed(mu, d_X, d_Y));
    return __result;
END_RCPP
}
