# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mat_G <- function(d_X, d_Y) {
    .Call('gwDist_mat_G', PACKAGE = 'gwDist', d_X, d_Y)
}

H_mu_typed <- function(mu, d_X, d_Y) {
    .Call('gwDist_H_mu_typed', PACKAGE = 'gwDist', mu, d_X, d_Y)
}

